# https://alacritty.org/config-alacritty.html

[font]
size = 14.0

[scrolling]
history = 0

[window]
padding = { x = 6, y = 6 }

[general]
import = [
    "~/.config/alacritty/spring_night.toml"
]

# Enable Shift+Return inside tmux on Alacritty.
# Tmux requests xterm modifyOtherKeys however Alacritty only implements Kitty keyboard protocol.
# https://github.com/alacritty/alacritty/issues/3101
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"
