[alias]
b = "build"
c = "check --tests --benches"
t = "test"
w = "watch"
wt = "watch -x test"
wc = ["watch", "-x", "clippy --all-targets --workspace"]
r = "run"
rr = "run --release"
cl = "clippy --all-targets --workspace"
