[alias]
b = "build"
c = "check --tests --benches"
t = "test"
w = "watch --why"
wt = "watch --why -x test"
wc = ["watch", "--why", "-x", "check --tests --benches"]
r = "run"
rr = "run --release"
cl = "clippy --tests --benches --workspace"
